### ISSUE TITLE
Data not loading after deploying to Vercel

### ISSUE THREAD

**Issue by Levi0219** [namezzy/Airbnb#1]
I can't get the data after deploying the project to Vercel, but locally it is loading the data fine!

**Comment by namezzy** [comment]
It's a cross-domain request. I put the data on a server that doesn't communicate with https, and when you request the data from vercel, your browser has a cross-domain request problem, which I'll fix later!

If you just want to see the effect of loading the data, open the link to the site you deployed and click on permissions then change the security to allow, you can try it out

![image](https://github.com/user-attachments/assets/df4590f8-1949-4641-80ee-f7850a4911be)
